### ISSUE TITLE
Download model issue

### ISSUE THREAD

**Issue by IzzulhaqFS** [Nico-Curti/Deepskin#1]
Hello,

I want to use deepskin for my final project. However, when I want to use wound_segmentation, an error like this occurs.

![image](https://github.com/Nico-Curti/Deepskin/assets/57482751/3fc60c7b-c99f-4d33-95d7-a9102a73b9de)

![image](https://github.com/Nico-Curti/Deepskin/assets/57482751/5cab2076-5f21-4891-a534-ca8e50f0726d)

How to solve this problem? Thanks

**Comment by Nico-Curti** [comment]
Hi @IzzulhaqFS,
The issue is due to a problem related to the google drive APIs.
In the latest [commit](https://github.com/Nico-Curti/Deepskin/commit/61f14b5d45b371181cb2d0fee96667a576612ef3) I moved from the by-hand request solution to the [gdown](https://github.com/wkentaro/gdown) package one, so now it should work properly.
Let me know if the issue persists.

**Comment by IzzulhaqFS** [comment]
It works now, thanks
